spring:
  datasource:
    url : jdbc:mysql://localhost:3306/nm_dev?autoReconnect=true&useSSL=true
    username : root
    password : ENC(ldKW5AJFE3JRf2FAP8Bn3g==)
    testWhileIdle : true
    validationQuery : SELECT 1
    initialize: false

  jpa:
    show-sql : false
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  
server:
  port: 8082
  
  
  
logging:
  level:
    org:
#      qpid: DEBUG
#      apache:
#        activemq: DEBUG
      springframework: INFO
    com:
      gcaa:
        nm: INFO
#          connector: INFO
#    sun:
#      security: DEBUG
#    java:
#      lang:
#        security: DEBUG
#    javax:
#      net:
#        security: DEBUG

gcaa:
# Local GCAA BRoker Properties
  broker:
    url: amqp://localhost:5672
    user: swimgw
    password: ENC(19h0955Nwta7EYi9kkicnsNjIxeGB7tG)
    house-keeping-days: 10
    # Set to true if gcaa.nm.* destinations are a topic
    insert-flight-plans-in-topic: false 
    qos-enabled: true

  # Eurocontrol NM Settings BRoker Properties
  nm:
    broker-url: amqps://publish.preops.nm.eurocontrol.int:5671?transport.trustAll=false&transport.verifyHost=true&transport.keyAlias=1
    ## Delay for listener. Listener checks for new Queue connecitons from database.
    listener:
      initDelay: 3000
      fixedDelay: 10000
    ## RecoveryInterval defines the wait between two retries of JMS connection. (Reconnection retries)      
    jmsrecovery-interval: 50000

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
