spring:
  datasource:
    url : jdbc:mysql://localhost:3306/nm_dev?autoReconnect=true&useSSL=true
    username : root
    password : ENC(ldKW5AJFE3JRf2FAP8Bn3g==)
    testWhileIdle : true
    validationQuery : SELECT 1
    initialize: false

  jpa:
    show-sql : false
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  
server:
  port: 8082
  
  
  
logging:
  level:
    org:
#      qpid: DEBUG
#      apache:
#        activemq: DEBUG
      springframework: INFO
    com:
      gcaa:
        nm: INFO
#          connector: INFO
#    sun:
#      security: DEBUG
#    java:
#      lang:
#        security: DEBUG
#    javax:
#      net:
#        security: DEBUG

gcaa:
# Local GCAA BRoker Properties
  broker:
    url: amqp://localhost:5672
    user: swimgw
    password: ENC(19h0955Nwta7EYi9kkicnsNjIxeGB7tG)
    house-keeping-days: 10
    # Set to true if gcaa.nm.* destinations are a topic
    insert-flight-plans-in-topic: false 
    qos-enabled: true

  # Eurocontrol NM Settings BRoker Properties
  nm:
    broker-url: amqps://publish.preops.nm.eurocontrol.int:5671?transport.trustAll=false&transport.verifyHost=true&transport.keyAlias=1
    ## Delay for listener. Listener checks for new Queue connecitons from database.
    listener:
      initDelay: 3000
      fixedDelay: 10000
    ## RecoveryInterval defines the wait between two retries of JMS connection. (Reconnection retries)      
    jmsrecovery-interval: 50000

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    
#    flight-plans-queue: gcaanm-msg-q
#    flight-data-queue: gcaa.nm.flight.data.q
#    msg-time-to-live: 21600000 # 6 hours time to live for a mesage published in GCAA Flight-Plan/DATA Queue
#javax:
#  net:
#      ssl:
#        keyStore: D:/work/projects/workspce/nm/cefi/cefitest/CC0000009204_500.jks
#        keyStorePassword: ******
#        trustStore: D:/work/projects/workspce/nm/cefi/cefitest/CC0000009204_500.jks
#        keyStorePassword: *****
#gcaa.security.ssl.key-store: D:/work/projects/workspce/nm/cefi/cefitest/CC0000009204_500.jks
#gcaa.security.ssl.key-store-password: ******
#gcaa.security.ssl.trust-store: D:/work/projects/workspce/nm/cefi/cefitest/CC0000009204_500.jks
#gcaa.security.ssl.trust-store-password: ******

#logging.level.org.springframework.jms=DEBUG
#logging.level.org.apache.qpid.amqp_1_0=DEBUG
#logging.level.org.apache.qpid.jms=DEBUG
#logging.level.org.apache.qpid=DEBUG
#logging.level.sun.security=DEBUG
#logging.level.java.lang.security=DEBUG
#logging.level.javax.net.security=DEBUG
#logging.level.java.net=DEBUG
#logging.level.javax.net.debug=DEBUG
#logging.level.org.apache.qpid.jms.transports.netty=DEBUG
# logging.level.org.apache.qpid.jms.JmsConnection=ERROR
#logging.level.com.gcaa.nm=DEBUG