//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddFlightsToMeasureRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddFlightsToMeasureRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{eurocontrol/cfmu/b2b/CommonServices}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataset" type="{eurocontrol/cfmu/b2b/CommonServices}Dataset"/&gt;
 *         &lt;element name="dayOfOperation" type="{eurocontrol/cfmu/b2b/CommonServices}DateYearMonthDay"/&gt;
 *         &lt;element name="flights" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" maxOccurs="100"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="FlightInMcdmOnly" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInMcdmOnly"/&gt;
 *                             &lt;element name="FlightInRerouting" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInRerouting"/&gt;
 *                             &lt;element name="FlightInRegulation" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInRegulation"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddFlightsToMeasureRequest", propOrder = {
    "dataset",
    "dayOfOperation",
    "flights"
})
public class AddFlightsToMeasureRequest
    extends Request
{

    @XmlElement(required = true)
    protected Dataset dataset;
    @XmlElement(required = true)
    protected String dayOfOperation;
    protected AddFlightsToMeasureRequest.Flights flights;

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link Dataset }
     *     
     */
    public Dataset getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataset }
     *     
     */
    public void setDataset(Dataset value) {
        this.dataset = value;
    }

    /**
     * Gets the value of the dayOfOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayOfOperation() {
        return dayOfOperation;
    }

    /**
     * Sets the value of the dayOfOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayOfOperation(String value) {
        this.dayOfOperation = value;
    }

    /**
     * Gets the value of the flights property.
     * 
     * @return
     *     possible object is
     *     {@link AddFlightsToMeasureRequest.Flights }
     *     
     */
    public AddFlightsToMeasureRequest.Flights getFlights() {
        return flights;
    }

    /**
     * Sets the value of the flights property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddFlightsToMeasureRequest.Flights }
     *     
     */
    public void setFlights(AddFlightsToMeasureRequest.Flights value) {
        this.flights = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" maxOccurs="100"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="FlightInMcdmOnly" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInMcdmOnly"/&gt;
     *                   &lt;element name="FlightInRerouting" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInRerouting"/&gt;
     *                   &lt;element name="FlightInRegulation" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInRegulation"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Flights {

        @XmlElement(required = true)
        protected List<AddFlightsToMeasureRequest.Flights.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AddFlightsToMeasureRequest.Flights.Item }
         * 
         * 
         */
        public List<AddFlightsToMeasureRequest.Flights.Item> getItem() {
            if (item == null) {
                item = new ArrayList<AddFlightsToMeasureRequest.Flights.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="FlightInMcdmOnly" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInMcdmOnly"/&gt;
         *         &lt;element name="FlightInRerouting" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInRerouting"/&gt;
         *         &lt;element name="FlightInRegulation" type="{eurocontrol/cfmu/b2b/FlowServices}FlightInRegulation"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "flightInMcdmOnly",
            "flightInRerouting",
            "flightInRegulation"
        })
        public static class Item {

            @XmlElement(name = "FlightInMcdmOnly")
            protected FlightInMcdmOnly flightInMcdmOnly;
            @XmlElement(name = "FlightInRerouting")
            protected FlightInRerouting flightInRerouting;
            @XmlElement(name = "FlightInRegulation")
            protected FlightInRegulation flightInRegulation;

            /**
             * Gets the value of the flightInMcdmOnly property.
             * 
             * @return
             *     possible object is
             *     {@link FlightInMcdmOnly }
             *     
             */
            public FlightInMcdmOnly getFlightInMcdmOnly() {
                return flightInMcdmOnly;
            }

            /**
             * Sets the value of the flightInMcdmOnly property.
             * 
             * @param value
             *     allowed object is
             *     {@link FlightInMcdmOnly }
             *     
             */
            public void setFlightInMcdmOnly(FlightInMcdmOnly value) {
                this.flightInMcdmOnly = value;
            }

            /**
             * Gets the value of the flightInRerouting property.
             * 
             * @return
             *     possible object is
             *     {@link FlightInRerouting }
             *     
             */
            public FlightInRerouting getFlightInRerouting() {
                return flightInRerouting;
            }

            /**
             * Sets the value of the flightInRerouting property.
             * 
             * @param value
             *     allowed object is
             *     {@link FlightInRerouting }
             *     
             */
            public void setFlightInRerouting(FlightInRerouting value) {
                this.flightInRerouting = value;
            }

            /**
             * Gets the value of the flightInRegulation property.
             * 
             * @return
             *     possible object is
             *     {@link FlightInRegulation }
             *     
             */
            public FlightInRegulation getFlightInRegulation() {
                return flightInRegulation;
            }

            /**
             * Sets the value of the flightInRegulation property.
             * 
             * @param value
             *     allowed object is
             *     {@link FlightInRegulation }
             *     
             */
            public void setFlightInRegulation(FlightInRegulation value) {
                this.flightInRegulation = value;
            }

        }

    }

}
