//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATFCMSituationCounts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATFCMSituationCounts"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nrLandedTraffic" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="nrAirborneTraffic" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="nrExpectedTraffic" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="nrFlightsUndefinedSlotCompliance" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="nrFlightsDepBeforeSlot" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="nrFlightsCompliedWithSlot" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="nrFlightsDepAfterSlot" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="suspendedFlightsDueToATFMMeasure" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="suspendedFlightsDueToFAM" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *         &lt;element name="flightsDelayedByMoreThan30Min" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATFCMSituationCounts", propOrder = {
    "nrLandedTraffic",
    "nrAirborneTraffic",
    "nrExpectedTraffic",
    "nrFlightsUndefinedSlotCompliance",
    "nrFlightsDepBeforeSlot",
    "nrFlightsCompliedWithSlot",
    "nrFlightsDepAfterSlot",
    "suspendedFlightsDueToATFMMeasure",
    "suspendedFlightsDueToFAM",
    "flightsDelayedByMoreThan30Min"
})
public class ATFCMSituationCounts {

    protected int nrLandedTraffic;
    protected int nrAirborneTraffic;
    protected int nrExpectedTraffic;
    protected int nrFlightsUndefinedSlotCompliance;
    protected int nrFlightsDepBeforeSlot;
    protected int nrFlightsCompliedWithSlot;
    protected int nrFlightsDepAfterSlot;
    protected int suspendedFlightsDueToATFMMeasure;
    protected int suspendedFlightsDueToFAM;
    protected int flightsDelayedByMoreThan30Min;

    /**
     * Gets the value of the nrLandedTraffic property.
     * 
     */
    public int getNrLandedTraffic() {
        return nrLandedTraffic;
    }

    /**
     * Sets the value of the nrLandedTraffic property.
     * 
     */
    public void setNrLandedTraffic(int value) {
        this.nrLandedTraffic = value;
    }

    /**
     * Gets the value of the nrAirborneTraffic property.
     * 
     */
    public int getNrAirborneTraffic() {
        return nrAirborneTraffic;
    }

    /**
     * Sets the value of the nrAirborneTraffic property.
     * 
     */
    public void setNrAirborneTraffic(int value) {
        this.nrAirborneTraffic = value;
    }

    /**
     * Gets the value of the nrExpectedTraffic property.
     * 
     */
    public int getNrExpectedTraffic() {
        return nrExpectedTraffic;
    }

    /**
     * Sets the value of the nrExpectedTraffic property.
     * 
     */
    public void setNrExpectedTraffic(int value) {
        this.nrExpectedTraffic = value;
    }

    /**
     * Gets the value of the nrFlightsUndefinedSlotCompliance property.
     * 
     */
    public int getNrFlightsUndefinedSlotCompliance() {
        return nrFlightsUndefinedSlotCompliance;
    }

    /**
     * Sets the value of the nrFlightsUndefinedSlotCompliance property.
     * 
     */
    public void setNrFlightsUndefinedSlotCompliance(int value) {
        this.nrFlightsUndefinedSlotCompliance = value;
    }

    /**
     * Gets the value of the nrFlightsDepBeforeSlot property.
     * 
     */
    public int getNrFlightsDepBeforeSlot() {
        return nrFlightsDepBeforeSlot;
    }

    /**
     * Sets the value of the nrFlightsDepBeforeSlot property.
     * 
     */
    public void setNrFlightsDepBeforeSlot(int value) {
        this.nrFlightsDepBeforeSlot = value;
    }

    /**
     * Gets the value of the nrFlightsCompliedWithSlot property.
     * 
     */
    public int getNrFlightsCompliedWithSlot() {
        return nrFlightsCompliedWithSlot;
    }

    /**
     * Sets the value of the nrFlightsCompliedWithSlot property.
     * 
     */
    public void setNrFlightsCompliedWithSlot(int value) {
        this.nrFlightsCompliedWithSlot = value;
    }

    /**
     * Gets the value of the nrFlightsDepAfterSlot property.
     * 
     */
    public int getNrFlightsDepAfterSlot() {
        return nrFlightsDepAfterSlot;
    }

    /**
     * Sets the value of the nrFlightsDepAfterSlot property.
     * 
     */
    public void setNrFlightsDepAfterSlot(int value) {
        this.nrFlightsDepAfterSlot = value;
    }

    /**
     * Gets the value of the suspendedFlightsDueToATFMMeasure property.
     * 
     */
    public int getSuspendedFlightsDueToATFMMeasure() {
        return suspendedFlightsDueToATFMMeasure;
    }

    /**
     * Sets the value of the suspendedFlightsDueToATFMMeasure property.
     * 
     */
    public void setSuspendedFlightsDueToATFMMeasure(int value) {
        this.suspendedFlightsDueToATFMMeasure = value;
    }

    /**
     * Gets the value of the suspendedFlightsDueToFAM property.
     * 
     */
    public int getSuspendedFlightsDueToFAM() {
        return suspendedFlightsDueToFAM;
    }

    /**
     * Sets the value of the suspendedFlightsDueToFAM property.
     * 
     */
    public void setSuspendedFlightsDueToFAM(int value) {
        this.suspendedFlightsDueToFAM = value;
    }

    /**
     * Gets the value of the flightsDelayedByMoreThan30Min property.
     * 
     */
    public int getFlightsDelayedByMoreThan30Min() {
        return flightsDelayedByMoreThan30Min;
    }

    /**
     * Sets the value of the flightsDelayedByMoreThan30Min property.
     * 
     */
    public void setFlightsDelayedByMoreThan30Min(int value) {
        this.flightsDelayedByMoreThan30Min = value;
    }

}
