//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATFCMSituationRegulation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATFCMSituationRegulation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="regulationId" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId"/&gt;
 *         &lt;element name="period" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeMinutePeriod"/&gt;
 *         &lt;element name="regulationState" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationState"/&gt;
 *         &lt;element name="regulationReason" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationReason"/&gt;
 *         &lt;element name="delay" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
 *         &lt;element name="nrImpactedFlights" type="{eurocontrol/cfmu/b2b/FlowServices}CountsValue"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATFCMSituationRegulation", propOrder = {
    "regulationId",
    "period",
    "regulationState",
    "regulationReason",
    "delay",
    "nrImpactedFlights"
})
public class ATFCMSituationRegulation {

    @XmlElement(required = true)
    protected String regulationId;
    @XmlElement(required = true)
    protected DateTimeMinutePeriod period;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String regulationState;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String regulationReason;
    @XmlElement(required = true)
    protected String delay;
    protected int nrImpactedFlights;

    /**
     * Gets the value of the regulationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationId() {
        return regulationId;
    }

    /**
     * Sets the value of the regulationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationId(String value) {
        this.regulationId = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeMinutePeriod }
     *     
     */
    public DateTimeMinutePeriod getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeMinutePeriod }
     *     
     */
    public void setPeriod(DateTimeMinutePeriod value) {
        this.period = value;
    }

    /**
     * Gets the value of the regulationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationState() {
        return regulationState;
    }

    /**
     * Sets the value of the regulationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationState(String value) {
        this.regulationState = value;
    }

    /**
     * Gets the value of the regulationReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationReason() {
        return regulationReason;
    }

    /**
     * Sets the value of the regulationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationReason(String value) {
        this.regulationReason = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelay(String value) {
        this.delay = value;
    }

    /**
     * Gets the value of the nrImpactedFlights property.
     * 
     */
    public int getNrImpactedFlights() {
        return nrImpactedFlights;
    }

    /**
     * Sets the value of the nrImpactedFlights property.
     * 
     */
    public void setNrImpactedFlights(int value) {
        this.nrImpactedFlights = value;
    }

}
