//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATFCMSituationDelays complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATFCMSituationDelays"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enRouteDelay" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
 *         &lt;element name="airportDelay" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
 *         &lt;element name="delaysPerRegulationReason" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" maxOccurs="15"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="key" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationReason"/&gt;
 *                             &lt;element name="value" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATFCMSituationDelays", propOrder = {
    "enRouteDelay",
    "airportDelay",
    "delaysPerRegulationReason"
})
public class ATFCMSituationDelays {

    @XmlElement(required = true)
    protected String enRouteDelay;
    @XmlElement(required = true)
    protected String airportDelay;
    protected ATFCMSituationDelays.DelaysPerRegulationReason delaysPerRegulationReason;

    /**
     * Gets the value of the enRouteDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnRouteDelay() {
        return enRouteDelay;
    }

    /**
     * Sets the value of the enRouteDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnRouteDelay(String value) {
        this.enRouteDelay = value;
    }

    /**
     * Gets the value of the airportDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportDelay() {
        return airportDelay;
    }

    /**
     * Sets the value of the airportDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportDelay(String value) {
        this.airportDelay = value;
    }

    /**
     * Gets the value of the delaysPerRegulationReason property.
     * 
     * @return
     *     possible object is
     *     {@link ATFCMSituationDelays.DelaysPerRegulationReason }
     *     
     */
    public ATFCMSituationDelays.DelaysPerRegulationReason getDelaysPerRegulationReason() {
        return delaysPerRegulationReason;
    }

    /**
     * Sets the value of the delaysPerRegulationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATFCMSituationDelays.DelaysPerRegulationReason }
     *     
     */
    public void setDelaysPerRegulationReason(ATFCMSituationDelays.DelaysPerRegulationReason value) {
        this.delaysPerRegulationReason = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" maxOccurs="15"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="key" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationReason"/&gt;
     *                   &lt;element name="value" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class DelaysPerRegulationReason {

        @XmlElement(required = true)
        protected List<ATFCMSituationDelays.DelaysPerRegulationReason.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ATFCMSituationDelays.DelaysPerRegulationReason.Item }
         * 
         * 
         */
        public List<ATFCMSituationDelays.DelaysPerRegulationReason.Item> getItem() {
            if (item == null) {
                item = new ArrayList<ATFCMSituationDelays.DelaysPerRegulationReason.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="key" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationReason"/&gt;
         *         &lt;element name="value" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Item {

            @XmlElement(required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String key;
            @XmlElement(required = true)
            protected String value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
