//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATFCMSituationReplyData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATFCMSituationReplyData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lastUpdated" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeSecond"/&gt;
 *         &lt;element name="counts" type="{eurocontrol/cfmu/b2b/FlowServices}ATFCMSituationCounts"/&gt;
 *         &lt;element name="delays" type="{eurocontrol/cfmu/b2b/FlowServices}ATFCMSituationDelays"/&gt;
 *         &lt;element name="regulations" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}ATFCMSituationRegulation" maxOccurs="10000" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATFCMSituationReplyData", propOrder = {
    "lastUpdated",
    "counts",
    "delays",
    "regulations"
})
public class ATFCMSituationReplyData {

    @XmlElement(required = true)
    protected String lastUpdated;
    @XmlElement(required = true)
    protected ATFCMSituationCounts counts;
    @XmlElement(required = true)
    protected ATFCMSituationDelays delays;
    protected ATFCMSituationReplyData.Regulations regulations;

    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdated(String value) {
        this.lastUpdated = value;
    }

    /**
     * Gets the value of the counts property.
     * 
     * @return
     *     possible object is
     *     {@link ATFCMSituationCounts }
     *     
     */
    public ATFCMSituationCounts getCounts() {
        return counts;
    }

    /**
     * Sets the value of the counts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATFCMSituationCounts }
     *     
     */
    public void setCounts(ATFCMSituationCounts value) {
        this.counts = value;
    }

    /**
     * Gets the value of the delays property.
     * 
     * @return
     *     possible object is
     *     {@link ATFCMSituationDelays }
     *     
     */
    public ATFCMSituationDelays getDelays() {
        return delays;
    }

    /**
     * Sets the value of the delays property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATFCMSituationDelays }
     *     
     */
    public void setDelays(ATFCMSituationDelays value) {
        this.delays = value;
    }

    /**
     * Gets the value of the regulations property.
     * 
     * @return
     *     possible object is
     *     {@link ATFCMSituationReplyData.Regulations }
     *     
     */
    public ATFCMSituationReplyData.Regulations getRegulations() {
        return regulations;
    }

    /**
     * Sets the value of the regulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATFCMSituationReplyData.Regulations }
     *     
     */
    public void setRegulations(ATFCMSituationReplyData.Regulations value) {
        this.regulations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}ATFCMSituationRegulation" maxOccurs="10000" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Regulations {

        protected List<ATFCMSituationRegulation> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ATFCMSituationRegulation }
         * 
         * 
         */
        public List<ATFCMSituationRegulation> getItem() {
            if (item == null) {
                item = new ArrayList<ATFCMSituationRegulation>();
            }
            return this.item;
        }

    }

}
