//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatasetType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DatasetType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FORECAST"/&gt;
 *     &lt;enumeration value="OPERATIONAL"/&gt;
 *     &lt;enumeration value="SIMULATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DatasetType", namespace = "eurocontrol/cfmu/b2b/CommonServices")
@XmlEnum
public enum DatasetType {

    FORECAST,
    OPERATIONAL,
    SIMULATION;

    public String value() {
        return name();
    }

    public static DatasetType fromValue(String v) {
        return valueOf(v);
    }

}
