//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightInRegulation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightInRegulation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{eurocontrol/cfmu/b2b/FlowServices}FlightInMeasure"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="regulationId" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId"/&gt;
 *         &lt;element name="newCto" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeMinute" minOccurs="0"/&gt;
 *         &lt;element name="newCtot" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeMinute" minOccurs="0"/&gt;
 *         &lt;element name="flightProposal"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightInRegulation", propOrder = {
    "regulationId",
    "newCto",
    "newCtot",
    "flightProposal"
})
public class FlightInRegulation
    extends FlightInMeasure
{

    @XmlElement(required = true)
    protected String regulationId;
    protected String newCto;
    protected String newCtot;
    protected boolean flightProposal;

    /**
     * Gets the value of the regulationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationId() {
        return regulationId;
    }

    /**
     * Sets the value of the regulationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationId(String value) {
        this.regulationId = value;
    }

    /**
     * Gets the value of the newCto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCto() {
        return newCto;
    }

    /**
     * Sets the value of the newCto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCto(String value) {
        this.newCto = value;
    }

    /**
     * Gets the value of the newCtot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCtot() {
        return newCtot;
    }

    /**
     * Sets the value of the newCtot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCtot(String value) {
        this.newCtot = value;
    }

    /**
     * Gets the value of the flightProposal property.
     * 
     */
    public boolean isFlightProposal() {
        return flightProposal;
    }

    /**
     * Sets the value of the flightProposal property.
     * 
     */
    public void setFlightProposal(boolean value) {
        this.flightProposal = value;
    }

}
