//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MCDMTopicUpdateRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MCDMTopicUpdateRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{eurocontrol/cfmu/b2b/CommonServices}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataset" type="{eurocontrol/cfmu/b2b/CommonServices}Dataset"/&gt;
 *         &lt;element name="date" type="{eurocontrol/cfmu/b2b/CommonServices}DateYearMonthDay"/&gt;
 *         &lt;element name="impersonatedUser" type="{eurocontrol/cfmu/b2b/CommonServices}AirNavigationUnitId"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="topic-MCDMHotspotTopic" type="{eurocontrol/cfmu/b2b/FlowServices}MCDMHotspotTopic"/&gt;
 *           &lt;element name="topic-MCDMFlightTopic" type="{eurocontrol/cfmu/b2b/FlowServices}MCDMFlightTopic"/&gt;
 *           &lt;element name="topic-MCDMMeasureTopic" type="{eurocontrol/cfmu/b2b/FlowServices}MCDMMeasureTopic"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MCDMTopicUpdateRequest", propOrder = {
    "dataset",
    "date",
    "impersonatedUser",
    "topicMCDMHotspotTopic",
    "topicMCDMFlightTopic",
    "topicMCDMMeasureTopic"
})
public class MCDMTopicUpdateRequest
    extends Request
{

    @XmlElement(required = true)
    protected Dataset dataset;
    @XmlElement(required = true)
    protected String date;
    @XmlElement(required = true)
    protected String impersonatedUser;
    @XmlElement(name = "topic-MCDMHotspotTopic")
    protected MCDMHotspotTopic topicMCDMHotspotTopic;
    @XmlElement(name = "topic-MCDMFlightTopic")
    protected MCDMFlightTopic topicMCDMFlightTopic;
    @XmlElement(name = "topic-MCDMMeasureTopic")
    protected MCDMMeasureTopic topicMCDMMeasureTopic;

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link Dataset }
     *     
     */
    public Dataset getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataset }
     *     
     */
    public void setDataset(Dataset value) {
        this.dataset = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the impersonatedUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpersonatedUser() {
        return impersonatedUser;
    }

    /**
     * Sets the value of the impersonatedUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpersonatedUser(String value) {
        this.impersonatedUser = value;
    }

    /**
     * Gets the value of the topicMCDMHotspotTopic property.
     * 
     * @return
     *     possible object is
     *     {@link MCDMHotspotTopic }
     *     
     */
    public MCDMHotspotTopic getTopicMCDMHotspotTopic() {
        return topicMCDMHotspotTopic;
    }

    /**
     * Sets the value of the topicMCDMHotspotTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCDMHotspotTopic }
     *     
     */
    public void setTopicMCDMHotspotTopic(MCDMHotspotTopic value) {
        this.topicMCDMHotspotTopic = value;
    }

    /**
     * Gets the value of the topicMCDMFlightTopic property.
     * 
     * @return
     *     possible object is
     *     {@link MCDMFlightTopic }
     *     
     */
    public MCDMFlightTopic getTopicMCDMFlightTopic() {
        return topicMCDMFlightTopic;
    }

    /**
     * Sets the value of the topicMCDMFlightTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCDMFlightTopic }
     *     
     */
    public void setTopicMCDMFlightTopic(MCDMFlightTopic value) {
        this.topicMCDMFlightTopic = value;
    }

    /**
     * Gets the value of the topicMCDMMeasureTopic property.
     * 
     * @return
     *     possible object is
     *     {@link MCDMMeasureTopic }
     *     
     */
    public MCDMMeasureTopic getTopicMCDMMeasureTopic() {
        return topicMCDMMeasureTopic;
    }

    /**
     * Sets the value of the topicMCDMMeasureTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCDMMeasureTopic }
     *     
     */
    public void setTopicMCDMMeasureTopic(MCDMMeasureTopic value) {
        this.topicMCDMMeasureTopic = value;
    }

}
