//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MCDMStatefulTopic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MCDMStatefulTopic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{eurocontrol/cfmu/b2b/FlowServices}MCDMTopic"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="measureId" type="{eurocontrol/cfmu/b2b/FlowServices}MeasureId" minOccurs="0"/&gt;
 *         &lt;element name="hotspotId" type="{eurocontrol/cfmu/b2b/FlowServices}HotspotId" minOccurs="0"/&gt;
 *         &lt;element name="state" type="{eurocontrol/cfmu/b2b/FlowServices}MCDMState" minOccurs="0"/&gt;
 *         &lt;element name="initiator" type="{eurocontrol/cfmu/b2b/CommonServices}AirNavigationUnitId" minOccurs="0"/&gt;
 *         &lt;element name="initiatorIsImplementer" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="userRolesAndApprovalStates" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}MCDMUserRoleAndApprovalState" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MCDMStatefulTopic", propOrder = {
    "measureId",
    "hotspotId",
    "state",
    "initiator",
    "initiatorIsImplementer",
    "userRolesAndApprovalStates"
})
@XmlSeeAlso({
    MCDMFlightTopic.class,
    MCDMMeasureTopic.class
})
public abstract class MCDMStatefulTopic
    extends MCDMTopic
{

    protected MeasureId measureId;
    protected HotspotId hotspotId;
    @XmlSchemaType(name = "anySimpleType")
    protected String state;
    protected String initiator;
    protected Boolean initiatorIsImplementer;
    protected MCDMStatefulTopic.UserRolesAndApprovalStates userRolesAndApprovalStates;

    /**
     * Gets the value of the measureId property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureId }
     *     
     */
    public MeasureId getMeasureId() {
        return measureId;
    }

    /**
     * Sets the value of the measureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureId }
     *     
     */
    public void setMeasureId(MeasureId value) {
        this.measureId = value;
    }

    /**
     * Gets the value of the hotspotId property.
     * 
     * @return
     *     possible object is
     *     {@link HotspotId }
     *     
     */
    public HotspotId getHotspotId() {
        return hotspotId;
    }

    /**
     * Sets the value of the hotspotId property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotspotId }
     *     
     */
    public void setHotspotId(HotspotId value) {
        this.hotspotId = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the initiator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiator() {
        return initiator;
    }

    /**
     * Sets the value of the initiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiator(String value) {
        this.initiator = value;
    }

    /**
     * Gets the value of the initiatorIsImplementer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitiatorIsImplementer() {
        return initiatorIsImplementer;
    }

    /**
     * Sets the value of the initiatorIsImplementer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitiatorIsImplementer(Boolean value) {
        this.initiatorIsImplementer = value;
    }

    /**
     * Gets the value of the userRolesAndApprovalStates property.
     * 
     * @return
     *     possible object is
     *     {@link MCDMStatefulTopic.UserRolesAndApprovalStates }
     *     
     */
    public MCDMStatefulTopic.UserRolesAndApprovalStates getUserRolesAndApprovalStates() {
        return userRolesAndApprovalStates;
    }

    /**
     * Sets the value of the userRolesAndApprovalStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCDMStatefulTopic.UserRolesAndApprovalStates }
     *     
     */
    public void setUserRolesAndApprovalStates(MCDMStatefulTopic.UserRolesAndApprovalStates value) {
        this.userRolesAndApprovalStates = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}MCDMUserRoleAndApprovalState" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class UserRolesAndApprovalStates {

        protected List<MCDMUserRoleAndApprovalState> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MCDMUserRoleAndApprovalState }
         * 
         * 
         */
        public List<MCDMUserRoleAndApprovalState> getItem() {
            if (item == null) {
                item = new ArrayList<MCDMUserRoleAndApprovalState>();
            }
            return this.item;
        }

    }

}
