//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasureId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasureId"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="REGULATION" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId"/&gt;
 *         &lt;element name="REROUTING" type="{eurocontrol/cfmu/b2b/FlowServices}ReroutingId"/&gt;
 *         &lt;element name="MCDM_ONLY" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureId", propOrder = {
    "regulation",
    "rerouting",
    "mcdmonly"
})
public class MeasureId {

    @XmlElement(name = "REGULATION")
    protected String regulation;
    @XmlElement(name = "REROUTING")
    protected String rerouting;
    @XmlElement(name = "MCDM_ONLY")
    protected String mcdmonly;

    /**
     * Gets the value of the regulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGULATION() {
        return regulation;
    }

    /**
     * Sets the value of the regulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGULATION(String value) {
        this.regulation = value;
    }

    /**
     * Gets the value of the rerouting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREROUTING() {
        return rerouting;
    }

    /**
     * Sets the value of the rerouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREROUTING(String value) {
        this.rerouting = value;
    }

    /**
     * Gets the value of the mcdmonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCDMONLY() {
        return mcdmonly;
    }

    /**
     * Sets the value of the mcdmonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCDMONLY(String value) {
        this.mcdmonly = value;
    }

}
