//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NMPlatform complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NMPlatform"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="executionEnvironment" type="{eurocontrol/cfmu/b2b/CommonServices}ExecutionEnvironment"/&gt;
 *         &lt;element name="applicationInstance"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="((([A-Z]{3}(_))[A-Z]{2})([A-Z]|[0-9]))"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NMPlatform", namespace = "eurocontrol/cfmu/b2b/CommonServices", propOrder = {
    "executionEnvironment",
    "applicationInstance"
})
public class NMPlatform {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ExecutionEnvironment executionEnvironment;
    @XmlElement(required = true)
    protected String applicationInstance;

    /**
     * Gets the value of the executionEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutionEnvironment }
     *     
     */
    public ExecutionEnvironment getExecutionEnvironment() {
        return executionEnvironment;
    }

    /**
     * Sets the value of the executionEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutionEnvironment }
     *     
     */
    public void setExecutionEnvironment(ExecutionEnvironment value) {
        this.executionEnvironment = value;
    }

    /**
     * Gets the value of the applicationInstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationInstance() {
        return applicationInstance;
    }

    /**
     * Sets the value of the applicationInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationInstance(String value) {
        this.applicationInstance = value;
    }

}
