//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTMV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTMV"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="trafficVolume" type="{eurocontrol/cfmu/b2b/FlowServices}TrafficVolumeId"/&gt;
 *         &lt;element name="otmvDuration" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute"/&gt;
 *         &lt;element name="peak" type="{eurocontrol/cfmu/b2b/FlowServices}OTMVPeak" minOccurs="0"/&gt;
 *         &lt;element name="sustained" type="{eurocontrol/cfmu/b2b/FlowServices}OTMVSustained" minOccurs="0"/&gt;
 *         &lt;element name="remark" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[a-zA-Z0-9_ \-\+\\\|\*=,.;:?!'@#$%^\(\)\[\]\{\}]{1,255}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTMV", propOrder = {
    "trafficVolume",
    "otmvDuration",
    "peak",
    "sustained",
    "remark"
})
public class OTMV {

    @XmlElement(required = true)
    protected String trafficVolume;
    @XmlElement(required = true)
    protected String otmvDuration;
    protected OTMVPeak peak;
    protected OTMVSustained sustained;
    protected String remark;

    /**
     * Gets the value of the trafficVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafficVolume() {
        return trafficVolume;
    }

    /**
     * Sets the value of the trafficVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafficVolume(String value) {
        this.trafficVolume = value;
    }

    /**
     * Gets the value of the otmvDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtmvDuration() {
        return otmvDuration;
    }

    /**
     * Sets the value of the otmvDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtmvDuration(String value) {
        this.otmvDuration = value;
    }

    /**
     * Gets the value of the peak property.
     * 
     * @return
     *     possible object is
     *     {@link OTMVPeak }
     *     
     */
    public OTMVPeak getPeak() {
        return peak;
    }

    /**
     * Sets the value of the peak property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTMVPeak }
     *     
     */
    public void setPeak(OTMVPeak value) {
        this.peak = value;
    }

    /**
     * Gets the value of the sustained property.
     * 
     * @return
     *     possible object is
     *     {@link OTMVSustained }
     *     
     */
    public OTMVSustained getSustained() {
        return sustained;
    }

    /**
     * Sets the value of the sustained property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTMVSustained }
     *     
     */
    public void setSustained(OTMVSustained value) {
        this.sustained = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

}
