//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "eurocontrol/cfmu/b2b/FlowServices")
package com.gcaa.nm.eurocontrol._2_5_0;
