//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlannedRunwayConfigurations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlannedRunwayConfigurations"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicabilityPeriod" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeMinutePeriod"/&gt;
 *         &lt;element name="dataSource" type="{eurocontrol/cfmu/b2b/FlowServices}PlanDataSource"/&gt;
 *         &lt;element name="runwayConfigurations" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}RunwayConfiguration" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlannedRunwayConfigurations", propOrder = {
    "applicabilityPeriod",
    "dataSource",
    "runwayConfigurations"
})
public class PlannedRunwayConfigurations {

    @XmlElement(required = true)
    protected DateTimeMinutePeriod applicabilityPeriod;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PlanDataSource dataSource;
    protected PlannedRunwayConfigurations.RunwayConfigurations runwayConfigurations;

    /**
     * Gets the value of the applicabilityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeMinutePeriod }
     *     
     */
    public DateTimeMinutePeriod getApplicabilityPeriod() {
        return applicabilityPeriod;
    }

    /**
     * Sets the value of the applicabilityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeMinutePeriod }
     *     
     */
    public void setApplicabilityPeriod(DateTimeMinutePeriod value) {
        this.applicabilityPeriod = value;
    }

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDataSource }
     *     
     */
    public PlanDataSource getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDataSource }
     *     
     */
    public void setDataSource(PlanDataSource value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the runwayConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link PlannedRunwayConfigurations.RunwayConfigurations }
     *     
     */
    public PlannedRunwayConfigurations.RunwayConfigurations getRunwayConfigurations() {
        return runwayConfigurations;
    }

    /**
     * Sets the value of the runwayConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlannedRunwayConfigurations.RunwayConfigurations }
     *     
     */
    public void setRunwayConfigurations(PlannedRunwayConfigurations.RunwayConfigurations value) {
        this.runwayConfigurations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}RunwayConfiguration" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class RunwayConfigurations {

        protected List<RunwayConfiguration> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RunwayConfiguration }
         * 
         * 
         */
        public List<RunwayConfiguration> getItem() {
            if (item == null) {
                item = new ArrayList<RunwayConfiguration>();
            }
            return this.item;
        }

    }

}
