//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegulationOrMCDMOnly complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulationOrMCDMOnly"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{eurocontrol/cfmu/b2b/FlowServices}Measure"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="regulationId" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId"/&gt;
 *         &lt;element name="reason" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationReason" minOccurs="0"/&gt;
 *         &lt;element name="location" type="{eurocontrol/cfmu/b2b/FlowServices}TrafficVolumeLocation" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="initialConstraints" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationInitialConstraint" maxOccurs="24" minOccurs="0"/&gt;
 *         &lt;element name="supplementaryConstraints" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationSupplementaryConstraint" maxOccurs="24" minOccurs="0"/&gt;
 *         &lt;element name="remark" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="autolink" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="linkedRegulations" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId" maxOccurs="10" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="noDelayWindow" type="{eurocontrol/cfmu/b2b/CommonServices}DurationHourMinute" minOccurs="0"/&gt;
 *         &lt;element name="updateCapacityRequired" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="updateTVActivationRequired" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulationOrMCDMOnly", propOrder = {
    "regulationId",
    "reason",
    "location",
    "initialConstraints",
    "supplementaryConstraints",
    "remark",
    "autolink",
    "linkedRegulations",
    "noDelayWindow",
    "updateCapacityRequired",
    "updateTVActivationRequired"
})
@XmlSeeAlso({
    MCDMOnly.class,
    Regulation.class,
    RegulationProposal.class
})
public abstract class RegulationOrMCDMOnly
    extends Measure
{

    @XmlElement(required = true)
    protected String regulationId;
    @XmlSchemaType(name = "anySimpleType")
    protected String reason;
    protected TrafficVolumeLocation location;
    protected List<RegulationInitialConstraint> initialConstraints;
    protected List<RegulationSupplementaryConstraint> supplementaryConstraints;
    protected String remark;
    protected Boolean autolink;
    protected RegulationOrMCDMOnly.LinkedRegulations linkedRegulations;
    protected String noDelayWindow;
    protected Boolean updateCapacityRequired;
    protected Boolean updateTVActivationRequired;

    /**
     * Gets the value of the regulationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationId() {
        return regulationId;
    }

    /**
     * Sets the value of the regulationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationId(String value) {
        this.regulationId = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficVolumeLocation }
     *     
     */
    public TrafficVolumeLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficVolumeLocation }
     *     
     */
    public void setLocation(TrafficVolumeLocation value) {
        this.location = value;
    }

    /**
     * Gets the value of the initialConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initialConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitialConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegulationInitialConstraint }
     * 
     * 
     */
    public List<RegulationInitialConstraint> getInitialConstraints() {
        if (initialConstraints == null) {
            initialConstraints = new ArrayList<RegulationInitialConstraint>();
        }
        return this.initialConstraints;
    }

    /**
     * Gets the value of the supplementaryConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplementaryConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplementaryConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegulationSupplementaryConstraint }
     * 
     * 
     */
    public List<RegulationSupplementaryConstraint> getSupplementaryConstraints() {
        if (supplementaryConstraints == null) {
            supplementaryConstraints = new ArrayList<RegulationSupplementaryConstraint>();
        }
        return this.supplementaryConstraints;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the autolink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutolink() {
        return autolink;
    }

    /**
     * Sets the value of the autolink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutolink(Boolean value) {
        this.autolink = value;
    }

    /**
     * Gets the value of the linkedRegulations property.
     * 
     * @return
     *     possible object is
     *     {@link RegulationOrMCDMOnly.LinkedRegulations }
     *     
     */
    public RegulationOrMCDMOnly.LinkedRegulations getLinkedRegulations() {
        return linkedRegulations;
    }

    /**
     * Sets the value of the linkedRegulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulationOrMCDMOnly.LinkedRegulations }
     *     
     */
    public void setLinkedRegulations(RegulationOrMCDMOnly.LinkedRegulations value) {
        this.linkedRegulations = value;
    }

    /**
     * Gets the value of the noDelayWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoDelayWindow() {
        return noDelayWindow;
    }

    /**
     * Sets the value of the noDelayWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoDelayWindow(String value) {
        this.noDelayWindow = value;
    }

    /**
     * Gets the value of the updateCapacityRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateCapacityRequired() {
        return updateCapacityRequired;
    }

    /**
     * Sets the value of the updateCapacityRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateCapacityRequired(Boolean value) {
        this.updateCapacityRequired = value;
    }

    /**
     * Gets the value of the updateTVActivationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateTVActivationRequired() {
        return updateTVActivationRequired;
    }

    /**
     * Sets the value of the updateTVActivationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateTVActivationRequired(Boolean value) {
        this.updateTVActivationRequired = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" type="{eurocontrol/cfmu/b2b/FlowServices}RegulationId" maxOccurs="10" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class LinkedRegulations {

        protected List<String> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getItem() {
            if (item == null) {
                item = new ArrayList<String>();
            }
            return this.item;
        }

    }

}
