//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Reply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reply"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requestReceptionTime" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeSecond" minOccurs="0"/&gt;
 *         &lt;element name="requestId" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sendTime" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeSecond" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{eurocontrol/cfmu/b2b/CommonServices}ReplyStatus"/&gt;
 *         &lt;element name="inputValidationErrors" type="{eurocontrol/cfmu/b2b/CommonServices}Error" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="outputValidationErrors" type="{eurocontrol/cfmu/b2b/CommonServices}Error" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="warnings" type="{eurocontrol/cfmu/b2b/CommonServices}Error" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="slaError" type="{eurocontrol/cfmu/b2b/CommonServices}Error" minOccurs="0"/&gt;
 *         &lt;element name="reason" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reply", namespace = "eurocontrol/cfmu/b2b/CommonServices", propOrder = {
    "requestReceptionTime",
    "requestId",
    "sendTime",
    "status",
    "inputValidationErrors",
    "outputValidationErrors",
    "warnings",
    "slaError",
    "reason"
})
@XmlSeeAlso({
    MessagePullReply.class,
    SubscriptionCreationReply.class,
    SubscriptionDeletionReply.class,
    SubscriptionHistoryReply.class,
    SubscriptionListReply.class,
    SubscriptionPauseReply.class,
    SubscriptionResumeReply.class,
    SubscriptionRetrievalReply.class,
    FileListReply.class,
    AddFlightsToMeasureReply.class,
    ATFCMSituationReply.class,
    CapacityPlanRetrievalReply.class,
    CapacityPlanUpdateReply.class,
/*    HotspotListReply.class,
    HotspotPlanUpdateReply.class,*/
    MCDMOnlyCancelReply.class,
    MCDMOnlyCreationReply.class,
    MCDMOnlyListReply.class,
    MCDMOnlyUpdateReply.class,
    MCDMStateUpdateReply.class,
    MCDMTopicListReply.class,
    MCDMTopicMessageRetrievalReply.class,
    MCDMTopicUpdateReply.class,
    MeasureOpLogRetrievalReply.class,
    OTMVPlanRetrievalReply.class,
    OTMVPlanUpdateReply.class,
    RegulationCancelReply.class,
    RegulationCreationReply.class,
    RegulationListReply.class,
    RegulationProposalFilingReply.class,
    RegulationProposalListReply.class,
    RegulationProposalRevocationReply.class,
    RegulationProposalUpdateReply.class,
    RegulationUpdateReply.class,
    RemoveFlightsFromMeasureReply.class,
    ReroutingCancelReply.class,
    ReroutingCreationReply.class,
    ReroutingListReply.class,
    ReroutingUpdateReply.class,
    RunwayConfigurationPlanRetrievalReply.class,
    RunwayConfigurationPlanUpdateReply.class,
    SectorConfigurationPlanRetrievalReply.class,
    SectorConfigurationPlanUpdateReply.class,
    TrafficCountsByAerodromeReply.class,
    TrafficCountsByAerodromeSetReply.class,
    TrafficCountsByAircraftOperatorReply.class,
    TrafficCountsByAirspaceReply.class,
    TrafficCountsByPointReply.class,
    TrafficCountsByTrafficVolumeReply.class,
    TrafficVolumeActivationPlanRetrievalReply.class,
    TrafficVolumeActivationPlanUpdateReply.class,
    AIMListReply.class,
    AIMRetrievalReply.class,
    NMB2BAddendaErrataReply.class,
    NMB2BReferenceManualsReply.class,
    NMB2BScenariosReply.class,
    NMB2BWSDLsReply.class,
    NMReleaseInformationReply.class
})
public abstract class Reply {

    protected String requestReceptionTime;
    protected String requestId;
    protected String sendTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ReplyStatus status;
    protected List<Error> inputValidationErrors;
    protected List<Error> outputValidationErrors;
    protected List<Error> warnings;
    protected Error slaError;
    protected String reason;

    /**
     * Gets the value of the requestReceptionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestReceptionTime() {
        return requestReceptionTime;
    }

    /**
     * Sets the value of the requestReceptionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestReceptionTime(String value) {
        this.requestReceptionTime = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the sendTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * Sets the value of the sendTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendTime(String value) {
        this.sendTime = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyStatus }
     *     
     */
    public ReplyStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyStatus }
     *     
     */
    public void setStatus(ReplyStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the inputValidationErrors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputValidationErrors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputValidationErrors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Error }
     * 
     * 
     */
    public List<Error> getInputValidationErrors() {
        if (inputValidationErrors == null) {
            inputValidationErrors = new ArrayList<Error>();
        }
        return this.inputValidationErrors;
    }

    /**
     * Gets the value of the outputValidationErrors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputValidationErrors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputValidationErrors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Error }
     * 
     * 
     */
    public List<Error> getOutputValidationErrors() {
        if (outputValidationErrors == null) {
            outputValidationErrors = new ArrayList<Error>();
        }
        return this.outputValidationErrors;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warnings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarnings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Error }
     * 
     * 
     */
    public List<Error> getWarnings() {
        if (warnings == null) {
            warnings = new ArrayList<Error>();
        }
        return this.warnings;
    }

    /**
     * Gets the value of the slaError property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getSlaError() {
        return slaError;
    }

    /**
     * Sets the value of the slaError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setSlaError(Error value) {
        this.slaError = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

}
