//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="endUserId" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="(([a-zA-Z]|[0-9])|(_)){0,30}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sendTime" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeSecond"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", namespace = "eurocontrol/cfmu/b2b/CommonServices", propOrder = {
    "endUserId",
    "sendTime"
})
@XmlSeeAlso({
    MessagePullRequest.class,
    SubscriptionCreationRequest.class,
    SubscriptionDeletionRequest.class,
    SubscriptionHistoryRequest.class,
    SubscriptionListRequest.class,
    SubscriptionPauseRequest.class,
    SubscriptionResumeRequest.class,
    SubscriptionRetrievalRequest.class,
    FileListRequest.class,
    AddFlightsToMeasureRequest.class,
    ATFCMSituationRequest.class,
    CapacityPlanUpdateRequest.class,
/*    HotspotListRequest.class,
    HotspotPlanUpdateRequest.class,*/
    MCDMOnlyCancelRequest.class,
    MCDMOnlyCreationRequest.class,
    MCDMOnlyUpdateRequest.class,
    MCDMStateUpdateRequest.class,
    MCDMTopicListRequest.class,
    MCDMTopicMessageRetrievalRequest.class,
    MCDMTopicUpdateRequest.class,
    MeasureOpLogRetrievalRequest.class,
    OTMVPlanUpdateRequest.class,
    RegulationCancelRequest.class,
    RegulationCreationRequest.class,
    RegulationProposalFilingRequest.class,
    RegulationProposalRevocationRequest.class,
    RegulationProposalUpdateRequest.class,
    RegulationUpdateRequest.class,
    RemoveFlightsFromMeasureRequest.class,
    ReroutingCancelRequest.class,
    ReroutingCreationRequest.class,
    ReroutingUpdateRequest.class,
    RunwayConfigurationPlanUpdateRequest.class,
    SectorConfigurationPlanUpdateRequest.class,
    TrafficVolumeActivationPlanUpdateRequest.class,
    MeasureListRequest.class,
    TacticalConfigurationRetrievalRequest.class,
    TrafficCountsRequest.class,
    AIMListRequest.class,
    AIMRetrievalRequest.class,
    NMB2BAddendaErrataRequest.class,
    NMB2BReferenceManualsRequest.class,
    NMB2BScenariosRequest.class,
    NMB2BWSDLsRequest.class,
    NMReleaseInformationRequest.class
})
public abstract class Request {

    protected String endUserId;
    @XmlElement(required = true)
    protected String sendTime;

    /**
     * Gets the value of the endUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserId() {
        return endUserId;
    }

    /**
     * Sets the value of the endUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserId(String value) {
        this.endUserId = value;
    }

    /**
     * Gets the value of the sendTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * Sets the value of the sendTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendTime(String value) {
        this.sendTime = value;
    }

}
