//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Subscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subscription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uuid" type="{eurocontrol/cfmu/b2b/CommonServices}UUID"/&gt;
 *         &lt;element name="release" type="{eurocontrol/cfmu/b2b/CommonServices}NMRelease"/&gt;
 *         &lt;element name="anuId" type="{eurocontrol/cfmu/b2b/CommonServices}AirNavigationUnitId"/&gt;
 *         &lt;element name="queueName" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}QueueName"/&gt;
 *         &lt;element name="topic" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}SubscriptionTopic"/&gt;
 *         &lt;element name="state" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}SubscriptionState"/&gt;
 *         &lt;element name="description" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value=".{1,500}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="creationDate" type="{eurocontrol/cfmu/b2b/CommonServices}DateTimeSecond"/&gt;
 *         &lt;element name="lastUpdatedBy"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value=".{1,100}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lastUpdatedOn" type="{eurocontrol/cfmu/b2b/CommonServices}Timestamp"/&gt;
 *         &lt;element name="lastUpdateReason" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}SubscriptionUpdateReason"/&gt;
 *         &lt;element name="lastUpdateComment" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="256"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="messageFilter-FlightPlanMessageFilter" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}FlightPlanMessageFilter"/&gt;
 *           &lt;element name="messageFilter-FlightDataMessageFilter" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}FlightDataMessageFilter"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="payloadConfiguration-EAUPPayloadConfiguration" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}EAUPPayloadConfiguration"/&gt;
 *           &lt;element name="payloadConfiguration-FlightDataPayloadConfiguration" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}FlightDataPayloadConfiguration"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subscription", namespace = "eurocontrol/cfmu/b2b/PublishsubscribeServices", propOrder = {
    "uuid",
    "release",
    "anuId",
    "queueName",
    "topic",
    "state",
    "description",
    "creationDate",
    "lastUpdatedBy",
    "lastUpdatedOn",
    "lastUpdateReason",
    "lastUpdateComment",
    "messageFilterFlightPlanMessageFilter",
    "messageFilterFlightDataMessageFilter",
    "payloadConfigurationEAUPPayloadConfiguration",
    "payloadConfigurationFlightDataPayloadConfiguration"
})
public class Subscription {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String release;
    @XmlElement(required = true)
    protected String anuId;
    @XmlElement(required = true)
    protected String queueName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String topic;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String state;
    protected String description;
    @XmlElement(required = true)
    protected String creationDate;
    @XmlElement(required = true)
    protected String lastUpdatedBy;
    @XmlElement(required = true)
    protected String lastUpdatedOn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lastUpdateReason;
    protected String lastUpdateComment;
    @XmlElement(name = "messageFilter-FlightPlanMessageFilter")
    protected FlightPlanMessageFilter messageFilterFlightPlanMessageFilter;
    @XmlElement(name = "messageFilter-FlightDataMessageFilter")
    protected FlightDataMessageFilter messageFilterFlightDataMessageFilter;
    @XmlElement(name = "payloadConfiguration-EAUPPayloadConfiguration")
    protected EAUPPayloadConfiguration payloadConfigurationEAUPPayloadConfiguration;
    @XmlElement(name = "payloadConfiguration-FlightDataPayloadConfiguration")
    protected FlightDataPayloadConfiguration payloadConfigurationFlightDataPayloadConfiguration;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelease(String value) {
        this.release = value;
    }

    /**
     * Gets the value of the anuId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnuId() {
        return anuId;
    }

    /**
     * Sets the value of the anuId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnuId(String value) {
        this.anuId = value;
    }

    /**
     * Gets the value of the queueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Sets the value of the queueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueueName(String value) {
        this.queueName = value;
    }

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopic(String value) {
        this.topic = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the lastUpdatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * Sets the value of the lastUpdatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedBy(String value) {
        this.lastUpdatedBy = value;
    }

    /**
     * Gets the value of the lastUpdatedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedOn() {
        return lastUpdatedOn;
    }

    /**
     * Sets the value of the lastUpdatedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedOn(String value) {
        this.lastUpdatedOn = value;
    }

    /**
     * Gets the value of the lastUpdateReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateReason() {
        return lastUpdateReason;
    }

    /**
     * Sets the value of the lastUpdateReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateReason(String value) {
        this.lastUpdateReason = value;
    }

    /**
     * Gets the value of the lastUpdateComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateComment() {
        return lastUpdateComment;
    }

    /**
     * Sets the value of the lastUpdateComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateComment(String value) {
        this.lastUpdateComment = value;
    }

    /**
     * Gets the value of the messageFilterFlightPlanMessageFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FlightPlanMessageFilter }
     *     
     */
    public FlightPlanMessageFilter getMessageFilterFlightPlanMessageFilter() {
        return messageFilterFlightPlanMessageFilter;
    }

    /**
     * Sets the value of the messageFilterFlightPlanMessageFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightPlanMessageFilter }
     *     
     */
    public void setMessageFilterFlightPlanMessageFilter(FlightPlanMessageFilter value) {
        this.messageFilterFlightPlanMessageFilter = value;
    }

    /**
     * Gets the value of the messageFilterFlightDataMessageFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FlightDataMessageFilter }
     *     
     */
    public FlightDataMessageFilter getMessageFilterFlightDataMessageFilter() {
        return messageFilterFlightDataMessageFilter;
    }

    /**
     * Sets the value of the messageFilterFlightDataMessageFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightDataMessageFilter }
     *     
     */
    public void setMessageFilterFlightDataMessageFilter(FlightDataMessageFilter value) {
        this.messageFilterFlightDataMessageFilter = value;
    }

    /**
     * Gets the value of the payloadConfigurationEAUPPayloadConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link EAUPPayloadConfiguration }
     *     
     */
    public EAUPPayloadConfiguration getPayloadConfigurationEAUPPayloadConfiguration() {
        return payloadConfigurationEAUPPayloadConfiguration;
    }

    /**
     * Sets the value of the payloadConfigurationEAUPPayloadConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAUPPayloadConfiguration }
     *     
     */
    public void setPayloadConfigurationEAUPPayloadConfiguration(EAUPPayloadConfiguration value) {
        this.payloadConfigurationEAUPPayloadConfiguration = value;
    }

    /**
     * Gets the value of the payloadConfigurationFlightDataPayloadConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link FlightDataPayloadConfiguration }
     *     
     */
    public FlightDataPayloadConfiguration getPayloadConfigurationFlightDataPayloadConfiguration() {
        return payloadConfigurationFlightDataPayloadConfiguration;
    }

    /**
     * Sets the value of the payloadConfigurationFlightDataPayloadConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightDataPayloadConfiguration }
     *     
     */
    public void setPayloadConfigurationFlightDataPayloadConfiguration(FlightDataPayloadConfiguration value) {
        this.payloadConfigurationFlightDataPayloadConfiguration = value;
    }

}
