//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 11:11:39 PM GST 
//


package com.gcaa.nm.eurocontrol._2_5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriptionCreationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionCreationRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{eurocontrol/cfmu/b2b/CommonServices}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="topic" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}SubscriptionTopic"/&gt;
 *         &lt;element name="description" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value=".{1,500}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="messageFilter-FlightPlanMessageFilter" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}FlightPlanMessageFilter"/&gt;
 *           &lt;element name="messageFilter-FlightDataMessageFilter" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}FlightDataMessageFilter"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="payloadConfiguration-EAUPPayloadConfiguration" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}EAUPPayloadConfiguration"/&gt;
 *           &lt;element name="payloadConfiguration-FlightDataPayloadConfiguration" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}FlightDataPayloadConfiguration"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="queueName" type="{eurocontrol/cfmu/b2b/PublishsubscribeServices}QueueName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "SubscriptionCreationRequest", namespace = "eurocontrol/cfmu/b2b/PublishsubscribeServices")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionCreationRequest", namespace = "eurocontrol/cfmu/b2b/PublishsubscribeServices", propOrder = {
    "topic",
    "description",
    "messageFilterFlightPlanMessageFilter",
    "messageFilterFlightDataMessageFilter",
    "payloadConfigurationEAUPPayloadConfiguration",
    "payloadConfigurationFlightDataPayloadConfiguration",
    "queueName"
})
public class SubscriptionCreationRequest
    extends Request
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String topic;
    protected String description;
    @XmlElement(name = "messageFilter-FlightPlanMessageFilter")
    protected FlightPlanMessageFilter messageFilterFlightPlanMessageFilter;
    @XmlElement(name = "messageFilter-FlightDataMessageFilter")
    protected FlightDataMessageFilter messageFilterFlightDataMessageFilter;
    @XmlElement(name = "payloadConfiguration-EAUPPayloadConfiguration")
    protected EAUPPayloadConfiguration payloadConfigurationEAUPPayloadConfiguration;
    @XmlElement(name = "payloadConfiguration-FlightDataPayloadConfiguration")
    protected FlightDataPayloadConfiguration payloadConfigurationFlightDataPayloadConfiguration;
    protected String queueName;

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopic(String value) {
        this.topic = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the messageFilterFlightPlanMessageFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FlightPlanMessageFilter }
     *     
     */
    public FlightPlanMessageFilter getMessageFilterFlightPlanMessageFilter() {
        return messageFilterFlightPlanMessageFilter;
    }

    /**
     * Sets the value of the messageFilterFlightPlanMessageFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightPlanMessageFilter }
     *     
     */
    public void setMessageFilterFlightPlanMessageFilter(FlightPlanMessageFilter value) {
        this.messageFilterFlightPlanMessageFilter = value;
    }

    /**
     * Gets the value of the messageFilterFlightDataMessageFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FlightDataMessageFilter }
     *     
     */
    public FlightDataMessageFilter getMessageFilterFlightDataMessageFilter() {
        return messageFilterFlightDataMessageFilter;
    }

    /**
     * Sets the value of the messageFilterFlightDataMessageFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightDataMessageFilter }
     *     
     */
    public void setMessageFilterFlightDataMessageFilter(FlightDataMessageFilter value) {
        this.messageFilterFlightDataMessageFilter = value;
    }

    /**
     * Gets the value of the payloadConfigurationEAUPPayloadConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link EAUPPayloadConfiguration }
     *     
     */
    public EAUPPayloadConfiguration getPayloadConfigurationEAUPPayloadConfiguration() {
        return payloadConfigurationEAUPPayloadConfiguration;
    }

    /**
     * Sets the value of the payloadConfigurationEAUPPayloadConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAUPPayloadConfiguration }
     *     
     */
    public void setPayloadConfigurationEAUPPayloadConfiguration(EAUPPayloadConfiguration value) {
        this.payloadConfigurationEAUPPayloadConfiguration = value;
    }

    /**
     * Gets the value of the payloadConfigurationFlightDataPayloadConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link FlightDataPayloadConfiguration }
     *     
     */
    public FlightDataPayloadConfiguration getPayloadConfigurationFlightDataPayloadConfiguration() {
        return payloadConfigurationFlightDataPayloadConfiguration;
    }

    /**
     * Sets the value of the payloadConfigurationFlightDataPayloadConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightDataPayloadConfiguration }
     *     
     */
    public void setPayloadConfigurationFlightDataPayloadConfiguration(FlightDataPayloadConfiguration value) {
        this.payloadConfigurationFlightDataPayloadConfiguration = value;
    }

    /**
     * Gets the value of the queueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Sets the value of the queueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueueName(String value) {
        this.queueName = value;
    }

}
