spring:
  datasource:
#    url : jdbc:mysql://localhost:3306/nm_dev?autoReconnect=true&useSSL=true
#    username : psi
#    password : ENC(o6fO7kgcwEst+jS6eyeVuj3sC0jVJv/2)
    testWhileIdle : true
    validationQuery : SELECT 1
    initialize: false
  profiles:
    active:
      - development
  jpa:
    show-sql : false
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  
server:
  port: 8080

logging:
  level:
    org:
#      apache:
#        activemq: DEBUG
      springframework: INFO
#        ws:
#          client:
#            MessageTracing: INFO
    com:
      gcaa:
        nm: INFO
#          connector: INFO

gcaa:
# Local GCAA BRoker Properties
  broker:
    url: amqp://localhost:5672
    user: swimgw
    password: ENC(dDhScXm4vGoXRxNB/Nm0xfgEw4AMMycX)
    house-keeping-days: 10
#    flight-plans-queue: gcaanm-msg-q
#    flight-data-queue: gcaa.nm.flight.data.q
    insert-flight-plans-in-topic: false # Set to true if gcaa.nm.* destinations are a topic
#    msg-time-to-live: 21600000 # 6 hours time to live for a mesage published in GCAA Flight-Plan/DATA Queue
    qos-enabled: true
  # Eurocontrol NM Settings BRoker Properties
  nm:
    endpoint-url: https://www.b2b.preops.nm.eurocontrol.int/B2B_PREOPS/gateway/spec/20.5.0
    broker-url: amqps://publish.preops.nm.eurocontrol.int:5671?transport.trustAll=false&transport.verifyHost=true&transport.keyAlias=1
    ## Delay for listener. Listener checks for new Queue connecitons from database.
    listener:
      initDelay: 3000
      fixedDelay: 10000
    ## Delay for subscription sync manager. Subscription in local database are synced for statuses with Eurocontrol NM.  
    subchecker:
      initDelay: 300
      fixedDelay: 30000
    ## RecoveryInterval defines the wait between two retries of JMS connection. (Reconnection retries)      
    jmsrecovery-interval: 50000

---   
spring : 
  datasource:
      url : jdbc:mysql://localhost:3306/nm_dev?autoReconnect=true&useSSL=true
      username : root
      password : ENC(l+u41FEqZu+hxR+hQPjqrA==)
  profiles: development

logging:
  level:
    com.gcaa.adi: debug 
---
spring : 
  datasource:
      url : jdbc:mysql://localhost:3306/adi_prod?autoReconnect=true&useSSL=true
      username : psi
      password : psi_prod
  profiles: production
