spring:
  datasource:
    url : jdbc:mysql://localhost:3306/nm_dev?autoReconnect=true&useSSL=true
    username : root
    password : root
    testWhileIdle : true
    validationQuery : SELECT 1

  jpa:
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  
server:
  port: 8180

logging:
  level:
    hello: INFO
    org:
      springframework:
        ws: TRACE

gcaa:
  security:
    ssl:
      key-store: D:/work/projects/workspce/nm/cefi/cefitest/CC0000009204_500.jks
      key-store-password: Qq3zlmvD0MTT
      trust-store: D:/work/projects/workspce/nm/cefi/cefitest/CC0000009204_500.jks
      trust-store-password: Qq3zlmvD0MTT
      endpoint-url: https://www.b2b.preops.nm.eurocontrol.int/B2B_PREOPS/gateway/spec/20.5.0
      
  nm:
    subchecker:
      initDelay: 300
      fixedDelay: 30000